MAIL_USERNAME=pawgrupo92024@gmail.com
MAIL_PASSWORD=eujd ybmr frcc fpsg
MAIL_PASS=46H3eJwoYqp38wa3y!H5epvxN5@i*s^
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_PROTOCOL=smtp
MAIL_DEBUG=true
MAIL_HAS_AUTH=true
MAIL_STARTTLS_ENABLE=true